"""Generate the contribution forms from the schema.

Run as: python -m scripts.build_forms

Two channels, one source of truth:

  .github/ISSUE_TEMPLATE/suggest-a-place.yml   for people with a GitHub account
  site/suggest.html                            for people without one

Both are generated rather than hand-written, because a form that asks different
questions from the ones the validator checks is worse than no form: someone
fills it in honestly and is rejected for it. Adding a field to the schema and
rerunning this is the whole change.

Both forms ask the four gates first, alone, with the answer required. Someone
who cannot tick them finds out in fifteen seconds instead of after writing a
paragraph, and what they are told is that the place is outside what this list
is for — not that it is a bad place.

Run with --check to verify the committed forms match the schema, which is what
CI does.
"""

import argparse
import html
import os
import sys

from scripts import schema as schema_mod

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ISSUE_FORM = os.path.join(ROOT, ".github", "ISSUE_TEMPLATE", "suggest-a-place.yml")
HTML_FORM = os.path.join(ROOT, "site", "suggest.html")

BANNER = "# Generated by scripts/build_forms.py from schema/place.schema.json. Do not edit by hand."

# Set this when the site goes up. Deliberately not a real address in the repo:
# putting one in a public static page is a decision to publish it, not a detail.
SUGGESTIONS_EMAIL = "SUGGESTIONS_EMAIL_NOT_SET"

INTRO = (
    "This is a list of central London places you can turn up to, stay a while, and pay "
    "nothing. Suggestions are read by a person before anything is published, so there is "
    "no rush and nothing goes live automatically."
)

DESCRIPTIVE = ("conversation", "activity", "seating", "setting")


def yaml_quote(text):
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def build_issue_form():
    gates = schema_mod.gates()
    fields = schema_mod.fields()
    lines = [
        BANNER,
        "name: Suggest a place",
        "description: Suggest somewhere you can turn up to, stay a while, and pay nothing.",
        "title: 'Suggestion: '",
        "labels: [suggestion]",
        "body:",
        "  - type: markdown",
        "    attributes:",
        "      value: |",
        "        %s" % INTRO,
        "",
        "        Please suggest places you have been to yourself. One sentence on why is",
        "        worth more than a full description.",
        "  - type: checkboxes",
        "    id: gates",
        "    attributes:",
        "      label: The four things a place has to be",
        "      description: >-",
        "        All four have to be true. If one of them is not, this is not the right list",
        "        for the place — which is a fact about the list, not about the place.",
        "    options:",
    ]
    for gate in gates:
        lines.append("      - label: %s" % yaml_quote(gate["confirm"]))
        lines.append("        required: true")

    lines += [
        "  - type: input",
        "    id: name",
        "    attributes:",
        "      label: What is it called?",
        "    validations:",
        "      required: true",
        "  - type: input",
        "    id: spot",
        "    attributes:",
        "      label: Which part of it, if the whole place is not the point?",
        "      description: >-",
        "        Optional. Somewhere like 'top floor, by the window' or 'the benches under",
        "        the canopy'. Leave empty for the place as a whole.",
        "  - type: input",
        "    id: where",
        "    attributes:",
        "      label: Where is it?",
        "      description: >-",
        "        A street and area is plenty. If you happen to know its OpenStreetMap link",
        "        or id, paste that instead and it saves a lookup — but it is not expected.",
        "    validations:",
        "      required: true",
        "  - type: textarea",
        "    id: why",
        "    attributes:",
        "      label: Why is it here?",
        "      description: >-",
        "        One sentence, up to 200 characters. What does this place not ask of you?",
        "    validations:",
        "      required: true",
    ]

    for name in DESCRIPTIVE:
        field = fields[name]
        meta = field.get("x-filter") or {}
        values = meta.get("values") or {}
        options = schema_mod.enum_values(name) or []
        lines += [
            "  - type: dropdown",
            "    id: %s" % name,
            "    attributes:",
            "      label: %s" % meta.get("label", name),
            "      options:",
        ]
        for value in options:
            described = values.get(value)
            label = "%s — %s" % (value, described) if described else value
            lines.append("        - %s" % yaml_quote(label))

    support = schema_mod.enum_values("support_options") or []
    lines += [
        "  - type: checkboxes",
        "    id: support_options",
        "    attributes:",
        "      label: Ways to support the place, if there are any",
        "      description: >-",
        "        Listed on the site and never ranked or ordered by. A place with none of",
        "        these is not worse than a place with four.",
        "    options:",
    ]
    for value in support:
        lines.append("      - label: %s" % yaml_quote(value.replace("_", " ")))

    lines += [
        "  - type: input",
        "    id: suggested_by",
        "    attributes:",
        "      label: How would you like to be credited?",
        "      description: Optional. Leave empty for no credit.",
        "",
    ]
    return "\n".join(lines)


def build_html_form():
    gates = schema_mod.gates()
    fields = schema_mod.fields()

    def esc(text):
        return html.escape(text, quote=True)

    parts = [
        "<!-- Generated by scripts/build_forms.py from schema/place.schema.json. Do not edit by hand. -->",
        '<!doctype html>',
        '<html lang="en-GB">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>Suggest a place — Central London Third Places</title>",
        "<style>",
        "  :root { color-scheme: light dark; --ink: #1a1a1a; --paper: #fdfdfb; --quiet: #5c5c5c;",
        "          --rule: #d8d8d2; --flag: #7a3b12; }",
        "  @media (prefers-color-scheme: dark) {",
        "    :root { --ink: #e8e6e1; --paper: #161614; --quiet: #a3a099; --rule: #34322e; --flag: #d9a273; }",
        "  }",
        "  body { background: var(--paper); color: var(--ink); margin: 0 auto; max-width: 34rem;",
        "         padding: 2rem 1.25rem 5rem; line-height: 1.55;",
        "         font-family: Georgia, 'Times New Roman', serif; }",
        "  h1 { font-size: 1.5rem; font-weight: normal; margin: 0 0 0.5rem; }",
        "  h2 { font-size: 1.05rem; font-weight: normal; margin: 2.5rem 0 0.25rem; }",
        "  p, li { color: var(--quiet); }",
        "  fieldset { border: 1px solid var(--rule); padding: 1rem 1.1rem; margin: 1.5rem 0; }",
        "  legend { padding: 0 0.4rem; color: var(--ink); }",
        "  label { display: block; margin: 0.9rem 0 0.2rem; color: var(--ink); }",
        "  .gate { display: grid; grid-template-columns: auto 1fr; gap: 0.6rem; align-items: start;",
        "          margin: 0.9rem 0; }",
        "  .gate input { margin: 0.35rem 0 0; }",
        "  .gate label { margin: 0; }",
        "  input[type=text], textarea, select { width: 100%; box-sizing: border-box; padding: 0.45rem;",
        "         border: 1px solid var(--rule); background: transparent; color: var(--ink);",
        "         font: inherit; font-size: 0.95rem; }",
        "  textarea { min-height: 4.5rem; }",
        "  .note { font-size: 0.88rem; }",
        "  button { font: inherit; padding: 0.55rem 1.1rem; margin-top: 1.5rem; cursor: pointer;",
        "           border: 1px solid var(--ink); background: transparent; color: var(--ink); }",
        "  #result { display: none; margin-top: 1.5rem; }",
        "  #result[data-shown] { display: block; }",
        "  #letter { width: 100%; min-height: 16rem; font-family: ui-monospace, Menlo, monospace;",
        "            font-size: 0.85rem; }",
        "  .aside { border-left: 2px solid var(--flag); padding-left: 0.9rem; }",
        "</style>",
        "</head>",
        "<body>",
        "<h1>Suggest a place</h1>",
        "<p>%s</p>" % esc(INTRO),
        '<p class="note">This form sends nothing anywhere. It writes out a message for you to '
        "copy into an email, because this site has no server and collects nothing about you.</p>",
        '<form id="suggest">',
        "<fieldset>",
        "<legend>The four things a place has to be</legend>",
        '<p class="note">All four have to be true. If one of them is not, this is not the right '
        "list for the place &mdash; which is a fact about the list, not about the place.</p>",
    ]

    for gate in gates:
        parts += [
            '<div class="gate">',
            '  <input type="checkbox" id="gate_%s" name="gate_%s" required>' % (gate["field"], gate["field"]),
            '  <label for="gate_%s">%s</label>' % (gate["field"], esc(gate["confirm"])),
            "</div>",
        ]

    parts += [
        "</fieldset>",
        "<label for=\"name\">What is it called?</label>",
        '<input type="text" id="name" name="name" required>',
        "<label for=\"spot\">Which part of it, if the whole place is not the point?</label>",
        '<p class="note">Optional &mdash; somewhere like &ldquo;top floor, by the window&rdquo;.</p>',
        '<input type="text" id="spot" name="spot" maxlength="60">',
        "<label for=\"where\">Where is it?</label>",
        '<p class="note">A street and area is plenty. An OpenStreetMap link saves a lookup, '
        "but is not expected.</p>",
        '<input type="text" id="where" name="where" required>',
        "<label for=\"why\">Why is it here?</label>",
        '<p class="note">One sentence, up to 200 characters. What does this place not ask of you?</p>',
        '<textarea id="why" name="why" maxlength="200" required></textarea>',
    ]

    for name in DESCRIPTIVE:
        meta = fields[name].get("x-filter") or {}
        values = meta.get("values") or {}
        parts += [
            '<label for="%s">%s</label>' % (name, esc(meta.get("label", name))),
            '<select id="%s" name="%s">' % (name, name),
            '  <option value="">not sure</option>',
        ]
        for value in schema_mod.enum_values(name) or []:
            described = values.get(value)
            label = "%s — %s" % (value, described) if described else value
            parts.append('  <option value="%s">%s</option>' % (esc(value), esc(label)))
        parts.append("</select>")

    parts += [
        "<fieldset>",
        "<legend>Ways to support the place, if there are any</legend>",
        '<p class="note">Listed on the site and never ranked or ordered by. A place with none '
        "of these is not worse than a place with four.</p>",
    ]
    for value in schema_mod.enum_values("support_options") or []:
        parts += [
            '<div class="gate">',
            '  <input type="checkbox" id="s_%s" name="support" value="%s">' % (value, esc(value)),
            '  <label for="s_%s">%s</label>' % (value, esc(value.replace("_", " "))),
            "</div>",
        ]

    parts += [
        "</fieldset>",
        '<label for="suggested_by">How would you like to be credited?</label>',
        '<p class="note">Optional. Leave empty for no credit.</p>',
        '<input type="text" id="suggested_by" name="suggested_by" maxlength="60">',
        '<button type="submit">Write the message</button>',
        "</form>",
        '<div id="result">',
        "<h2>Copy this into an email</h2>",
        '<p class="note">Send it to <strong>%s</strong>. Nothing has been sent for you.</p>' % esc(SUGGESTIONS_EMAIL),
        '<textarea id="letter" readonly></textarea>',
        "</div>",
        "<script>",
        "  // The browser enforces the four gates: a required checkbox that is not ticked",
        "  // stops submission on its own, with no script involved.",
        "  document.getElementById('suggest').addEventListener('submit', function (event) {",
        "    event.preventDefault();",
        "    var form = event.target;",
        "    var value = function (n) { var el = form.elements[n]; return el ? el.value.trim() : ''; };",
        "    var support = Array.prototype.slice",
        "      .call(form.querySelectorAll('input[name=support]:checked'))",
        "      .map(function (el) { return el.value; });",
        "    var lines = [",
        "      'A place to suggest', '',",
        "      'Name: ' + value('name'),",
        "      'Spot: ' + (value('spot') || '(the place as a whole)'),",
        "      'Where: ' + value('where'), '',",
        "      'Why: ' + value('why'), '',",
        "      'I confirm all four:',",
    ]
    for gate in gates:
        parts.append("      '  - %s'," % gate["confirm"].replace("'", "\\'"))
    parts += [
        "      '',",
    ]
    for name in DESCRIPTIVE:
        parts.append("      '%s: ' + (value('%s') || 'not sure')," % (name, name))
    parts += [
        "      '',",
        "      'Ways to support: ' + (support.length ? support.join(', ') : 'none that I noticed'),",
        "      'Credit me as: ' + (value('suggested_by') || '(no credit)')",
        "    ];",
        "    var out = document.getElementById('letter');",
        "    out.value = lines.join('\\n');",
        "    document.getElementById('result').setAttribute('data-shown', '');",
        "    out.focus();",
        "    out.select();",
        "  });",
        "</script>",
        "</body>",
        "</html>",
        "",
    ]
    return "\n".join(parts)


TARGETS = [(ISSUE_FORM, build_issue_form), (HTML_FORM, build_html_form)]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="Fail if the committed forms do not match the schema.")
    args = parser.parse_args(argv)

    stale = []
    for path, build in TARGETS:
        wanted = build()
        current = open(path).read() if os.path.exists(path) else None
        rel = os.path.relpath(path, ROOT)
        if args.check:
            if current != wanted:
                stale.append(rel)
            continue
        directory = os.path.dirname(path)
        if not os.path.isdir(directory):
            os.makedirs(directory)
        with open(path, "w") as fh:
            fh.write(wanted)
        print("%s %s" % ("unchanged" if current == wanted else "wrote    ", rel))

    if args.check:
        if stale:
            print("These forms no longer match schema/place.schema.json:\n")
            for rel in stale:
                print("  %s" % rel)
            print("\nRun: python -m scripts.build_forms")
            return 1
        print("Both contribution forms match the schema.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
