"""Generate the contribution forms from the schema and scripts/form_spec.py.

Run as: python -m scripts.build_forms

  .github/ISSUE_TEMPLATE/suggest-a-place.yml   for people with a GitHub account
  site/suggest.html                            for people without one

Generated rather than hand-written, because a form that asks different
questions from the ones the validator checks is worse than no form: someone
fills it in honestly and is rejected for it.

Both ask the four gates first, alone, with the answer required. Someone who
cannot tick them finds out in fifteen seconds instead of after writing a
paragraph, and what they are told is that the place is outside what this list
is for — not that it is a bad place.

--check verifies the committed forms match, which is what CI does.
"""

import argparse
import html
import os
import sys

from scripts import form_spec, schema as schema_mod

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ISSUE_FORM = os.path.join(ROOT, ".github", "ISSUE_TEMPLATE", "suggest-a-place.yml")
HTML_FORM = os.path.join(ROOT, "site", "suggest.html")

BANNER = "# Generated by scripts/build_forms.py from schema/place.schema.json. Do not edit by hand."

SUGGESTIONS_EMAIL = "hello@cormacauty.com"
ISSUE_FORM_URL = ("https://github.com/lingerinlondon/lingerinlondon.github.io"
                  "/issues/new?template=suggest-a-place.yml")

INTRO = (
    "This is a list of central London places you can turn up to, stay a while, and pay "
    "nothing. Suggestions are read by a person before anything is published, so there is "
    "no rush and nothing goes live automatically."
)

PREAMBLE = (
    "Please suggest places you have been to yourself. The questions below assume you have "
    "sat there — they are not answerable from a map."
)


def yq(text):
    return '"%s"' % text.replace("\\", "\\\\").replace('"', '\\"')


def esc(text):
    return html.escape(str(text), quote=True)


def build_issue_form():
    lines = [
        BANNER,
        "name: Suggest a place",
        "description: Suggest somewhere you can turn up to, stay a while, and pay nothing.",
        "title: 'Suggestion: '",
        "labels: [suggestion]",
        "body:",
        "  - type: markdown",
        "    attributes:",
        "      value: |",
        "        %s" % INTRO,
        "",
        "        %s" % PREAMBLE,
    ]

    for q in form_spec.questions():
        if q["kind"] == "gates":
            lines += [
                "  - type: checkboxes",
                "    id: gates",
                "    attributes:",
                "      label: %s" % q["label"],
                "      description: >-",
                "        %s" % q["note"],
                "      options:",
            ]
            for gate in schema_mod.gates():
                lines.append("        - label: %s" % yq(gate["confirm"]))
                lines.append("          required: true")
            continue

        kind = {"input": "input", "date": "input", "textarea": "textarea",
                "dropdown": "dropdown", "checkboxes": "checkboxes"}[q["kind"]]
        lines += ["  - type: %s" % kind, "    id: %s" % q["key"], "    attributes:",
                  "      label: %s" % yq(q["label"])]

        note = q.get("note")
        if q["kind"] == "date":
            note = "%s Written as a date, like %s." % (note, form_spec.oldest_acceptable().isoformat())
        if note:
            lines += ["      description: >-", "        %s" % note]

        if q["kind"] == "dropdown":
            lines.append("      options:")
            for value in q["options"]:
                lines.append("        - %s" % yq(
                    form_spec.option_label(value, q["values"].get(value))))
        elif q["kind"] == "checkboxes":
            lines.append("      options:")
            for value in q["options"]:
                lines.append("        - label: %s" % yq(value.replace("_", " ")))
        elif q.get("required"):
            lines += ["    validations:", "      required: true"]

    lines.append("")
    return "\n".join(lines)


CSS = [
    "  :root { color-scheme: light dark; --ink: #1a1a1a; --paper: #fdfdfb; --quiet: #5c5c5c;",
    "          --rule: #d8d8d2; }",
    "  @media (prefers-color-scheme: dark) {",
    "    :root { --ink: #e8e6e1; --paper: #161614; --quiet: #a3a099; --rule: #34322e; }",
    "  }",
    "  * { box-sizing: border-box; }",
    "  body { background: var(--paper); color: var(--ink); margin: 0 auto; max-width: 34rem;",
    "         padding: 2rem 1.25rem 5rem; line-height: 1.55;",
    "         font-family: Georgia, 'Times New Roman', serif; }",
    "  h1 { font-size: 1.5rem; font-weight: normal; margin: 0 0 0.5rem; }",
    "  h2 { font-size: 1.05rem; font-weight: normal; margin: 2.5rem 0 0.25rem; }",
    "  p, li { color: var(--quiet); }",
    "  fieldset { border: 1px solid var(--rule); padding: 1rem 1.1rem; margin: 1.5rem 0; }",
    "  legend { padding: 0 0.4rem; color: var(--ink); }",
    "  label { display: block; margin: 0.9rem 0 0.2rem; color: var(--ink); }",
    "  .gate { display: grid; grid-template-columns: auto 1fr; gap: 0.6rem; align-items: start;",
    "          margin: 0.9rem 0; }",
    "  .gate input { margin: 0.35rem 0 0; }",
    "  .gate label { margin: 0; }",
    "  input[type=text], input[type=date], textarea, select { width: 100%;",
    "         box-sizing: border-box; padding: 0.45rem; border: 1px solid var(--rule);",
    "         background: transparent; color: var(--ink); font: inherit; font-size: 0.95rem; }",
    "  textarea { min-height: 4.5rem; }",
    "  .note { font-size: 0.88rem; }",
    "  .route { border-top: 1px solid var(--rule); border-bottom: 1px solid var(--rule);",
    "           padding: 0.8rem 0; margin: 1.8rem 0; font-size: 0.94rem; }",
    "  .route p { margin: 0.5rem 0; }",
    "  button { font: inherit; padding: 0.55rem 1.1rem; margin-top: 1.5rem; cursor: pointer;",
    "           border: 1px solid var(--ink); background: transparent; color: var(--ink); }",
    "  #result { display: none; margin-top: 1.5rem; }",
    "  #result[data-shown] { display: block; }",
    "  #letter { width: 100%; min-height: 16rem; font-family: ui-monospace, Menlo, monospace;",
    "            font-size: 0.85rem; }",
]


def build_html_form():
    questions = form_spec.questions()
    parts = [
        "<!-- Generated by scripts/build_forms.py from schema/place.schema.json. Do not edit by hand. -->",
        "<!doctype html>",
        '<html lang="en-GB">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>Suggest a place — Linger in London</title>",
        "<style>",
    ] + CSS + [
        "</style>",
        "</head>",
        "<body>",
        "<h1>Suggest a place</h1>",
        "<p>%s</p>" % esc(INTRO),
        "<p>%s</p>" % esc(PREAMBLE),
        '<div class="route">',
        "<p><strong>If you have a GitHub account</strong>, "
        '<a href="%s">use the form there</a> instead. It asks the same questions and '
        "starts the change off on its own, which saves a step at both ends.</p>" % ISSUE_FORM_URL,
        "<p>No account, or would rather not? The form below is for you. It sends nothing "
        "anywhere &mdash; it writes out a message for you to copy into an email, because this "
        "site has no server and collects nothing about you.</p>",
        "</div>",
        '<form id="suggest">',
    ]

    for q in questions:
        key = q["key"]
        if q["kind"] == "gates":
            parts += ["<fieldset>", "<legend>%s</legend>" % esc(q["label"]),
                      '<p class="note">%s</p>' % esc(q["note"])]
            for gate in schema_mod.gates():
                parts += [
                    '<div class="gate">',
                    '  <input type="checkbox" id="gate_%s" name="gate_%s" required>'
                    % (gate["field"], gate["field"]),
                    '  <label for="gate_%s">%s</label>' % (gate["field"], esc(gate["confirm"])),
                    "</div>",
                ]
            parts.append("</fieldset>")
            continue

        if q["kind"] == "checkboxes":
            parts += ["<fieldset>", "<legend>%s</legend>" % esc(q["label"]),
                      '<p class="note">%s</p>' % esc(q["note"])]
            for value in q["options"]:
                parts += [
                    '<div class="gate">',
                    '  <input type="checkbox" id="s_%s" name="support" value="%s">'
                    % (value, esc(value)),
                    '  <label for="s_%s">%s</label>' % (value, esc(value.replace("_", " "))),
                    "</div>",
                ]
            parts.append("</fieldset>")
            continue

        parts.append('<label for="%s">%s</label>' % (key, esc(q["label"])))
        if q.get("note"):
            parts.append('<p class="note">%s</p>' % esc(q["note"]))
        required = " required" if q.get("required") else ""

        if q["kind"] == "input":
            parts.append('<input type="text" id="%s" name="%s"%s>' % (key, key, required))
        elif q["kind"] == "date":
            # The browser refuses a visit older than a year, or one in the future.
            parts.append('<input type="date" id="%s" name="%s" min="%s" max="%s"%s>'
                         % (key, key, form_spec.oldest_acceptable().isoformat(),
                            __import__("datetime").date.today().isoformat(), required))
        elif q["kind"] == "textarea":
            parts.append('<textarea id="%s" name="%s" maxlength="200"%s></textarea>'
                         % (key, key, required))
        elif q["kind"] == "dropdown":
            parts.append('<select id="%s" name="%s">' % (key, key))
            parts.append('  <option value="">not sure</option>')
            for value in q["options"]:
                parts.append('  <option value="%s">%s</option>'
                             % (esc(value),
                                esc(form_spec.option_label(value, q["values"].get(value)))))
            parts.append("</select>")

    parts += [
        '<button type="submit">Write the message</button>',
        "</form>",
        '<div id="result">',
        "<h2>Copy this into an email</h2>",
        '<p class="note">Nothing has been sent for you. Copy the message below and send it '
        'to <a href="mailto:%s">%s</a>.</p>' % (esc(SUGGESTIONS_EMAIL), esc(SUGGESTIONS_EMAIL)),
        '<textarea id="letter" readonly></textarea>',
        "</div>",
        "<script>",
        "  // The browser enforces the gates and the date range: a required checkbox that is",
        "  // not ticked, or a date outside min/max, stops submission with no script involved.",
        "  document.getElementById('suggest').addEventListener('submit', function (event) {",
        "    event.preventDefault();",
        "    var form = event.target;",
        "    var value = function (n) { var el = form.elements[n]; return el ? el.value.trim() : ''; };",
        "    var support = Array.prototype.slice",
        "      .call(form.querySelectorAll('input[name=support]:checked'))",
        "      .map(function (el) { return el.value; });",
        "    var lines = ['A place to suggest', ''];",
    ]
    for q in questions:
        if q["kind"] == "gates":
            parts.append("    lines.push('I confirm all four:');")
            for gate in schema_mod.gates():
                parts.append("    lines.push('  - %s');" % gate["confirm"].replace("'", "\\'"))
            parts.append("    lines.push('');")
        elif q["kind"] == "checkboxes":
            parts.append("    lines.push('%s: ' + (support.length ? support.join(', ') "
                         ": 'none that I noticed'));" % q["label"].replace("'", "\\'"))
        else:
            parts.append("    lines.push('%s ' + (value('%s') || '(not given)'));"
                         % (q["label"].replace("'", "\\'"), q["key"]))
    parts += [
        "    var out = document.getElementById('letter');",
        "    out.value = lines.join('\\n');",
        "    document.getElementById('result').setAttribute('data-shown', '');",
        "    out.focus();",
        "    out.select();",
        "  });",
        "</script>",
        "</body>",
        "</html>",
        "",
    ]
    return "\n".join(parts)


TARGETS = [(ISSUE_FORM, build_issue_form), (HTML_FORM, build_html_form)]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="Fail if the committed forms do not match the schema.")
    args = parser.parse_args(argv)

    stale = []
    for path, build in TARGETS:
        wanted = build()
        current = open(path).read() if os.path.exists(path) else None
        rel = os.path.relpath(path, ROOT)
        if args.check:
            if current != wanted:
                stale.append(rel)
            continue
        directory = os.path.dirname(path)
        if not os.path.isdir(directory):
            os.makedirs(directory)
        with open(path, "w") as fh:
            fh.write(wanted)
        print("%s %s" % ("unchanged" if current == wanted else "wrote    ", rel))

    if args.check:
        if stale:
            print("These forms no longer match the schema:\n")
            for rel in stale:
                print("  %s" % rel)
            print("\nRun: python -m scripts.build_forms")
            return 1
        print("Both contribution forms match the schema.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
